In [ ]:
!wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1gWmW9FFCCOTWDRdpN0Cq-pfUe67KmX5Y' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1gWmW9FFCCOTWDRdpN0Cq-pfUe67KmX5Y" -O RSData.zip && rm -rf /tmp/cookies.txt
#https://drive.google.com/file/d/1gWmW9FFCCOTWDRdpN0Cq-pfUe67KmX5Y/view?usp=sharing
!unzip RSData.zip

--2023-10-24 08:23:09--  https://docs.google.com/uc?export=download&confirm=t&id=1gWmW9FFCCOTWDRdpN0Cq-pfUe67KmX5Y
Resolving docs.google.com (docs.google.com)... 74.125.26.102, 74.125.26.113, 74.125.26.139, ...
Connecting to docs.google.com (docs.google.com)|74.125.26.102|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://doc-04-44-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/c9ls85k3k7k08strqilpomrdeiabnc2c/1698135750000/07988131849474548919/*/1gWmW9FFCCOTWDRdpN0Cq-pfUe67KmX5Y?e=download&uuid=0e50174c-c545-4c4e-9977-ed6a25a3de48 [following]
Warning: wildcards not supported in HTTP.
--2023-10-24 08:23:09--  https://doc-04-44-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/c9ls85k3k7k08strqilpomrdeiabnc2c/1698135750000/07988131849474548919/*/1gWmW9FFCCOTWDRdpN0Cq-pfUe67KmX5Y?e=download&uuid=0e50174c-c545-4c4e-9977-ed6a25a3de48
Resolving doc-04-44-docs.googleusercontent.com (doc-04-44-docs.googleusercontent.com)... 172.217.193.132, 2607:f8b0:400c:c03::84
Connecting to doc-04-44-docs.googleusercontent.com (doc-04-44-docs.googleusercontent.com)|172.217.193.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 29068370 (28M) [application/x-zip-compressed]
Saving to: ‘RSData.zip’

RSData.zip          100%[===================>]  27.72M   145MB/s    in 0.2s

2023-10-24 08:23:09 (145 MB/s) - ‘RSData.zip’ saved [29068370/29068370]

Archive:  RSData.zip
  inflating: user_item.csv
  inflating: user_tag.csv
  inflating: user_user.csv
   creating: hetrec2011-delicious-2k/
  inflating: hetrec2011-delicious-2k/bookmarks.csv
  inflating: hetrec2011-delicious-2k/bookmarks.dat
  inflating: hetrec2011-delicious-2k/bookmark_tags.csv
  inflating: hetrec2011-delicious-2k/bookmark_tags.dat
  inflating: hetrec2011-delicious-2k/readme.txt
  inflating: hetrec2011-delicious-2k/tags.csv
  inflating: hetrec2011-delicious-2k/tags.dat
  inflating: hetrec2011-delicious-2k/user_contacts-timestamps.dat
  inflating: hetrec2011-delicious-2k/user_contacts.csv
  inflating: hetrec2011-delicious-2k/user_contacts.dat
  inflating: hetrec2011-delicious-2k/user_taggedbookmarks-timestamps.dat
  inflating: hetrec2011-delicious-2k/user_taggedbookmarks.csv
  inflating: hetrec2011-delicious-2k/user_taggedbookmarks.dat
   creating: hetrec2011-lastfm-2k/
  inflating: hetrec2011-lastfm-2k/artists.csv
  inflating: hetrec2011-lastfm-2k/artists.dat
  inflating: hetrec2011-lastfm-2k/readme.txt
  inflating: hetrec2011-lastfm-2k/tags.csv
  inflating: hetrec2011-lastfm-2k/tags.dat
  inflating: hetrec2011-lastfm-2k/user_artists.csv
  inflating: hetrec2011-lastfm-2k/user_artists.dat
  inflating: hetrec2011-lastfm-2k/user_friends.csv
  inflating: hetrec2011-lastfm-2k/user_friends.dat
  inflating: hetrec2011-lastfm-2k/user_taggedartists-timestamps.dat
  inflating: hetrec2011-lastfm-2k/user_taggedartists.csv

##User-User

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
user_friends = pd.read_csv('/content/hetrec2011-lastfm-2k/user_friends.csv')
user_friends

       userID  friendID
0           2       275
1           2       428
2           2       515
3           2       761
4           2       831
...       ...       ...
25429    2099      1801
25430    2099      2006
25431    2099      2016
25432    2100       586
25433    2100       607

[25434 rows x 2 columns]

In [ ]:
# Create a pivot table with index starting at zero and ending at 2100
pivot_table = user_friends.pivot_table(index=['userID'], columns='friendID', aggfunc='size', fill_value=0)

# Reindex the pivot table to have index from 0 to 2100
# user_friends_df = pivot_table.reindex(range(1, 2101), fill_value=0, axis=0).reindex(range(1, 2101), fill_value=0, axis=1)
user_friends_df = pivot_table

# Reset column names to be 'userID' and 'friendID'
user_friends_df.columns.name = 'friendID'
user_friends_df.index.name = 'userID'

print(user_friends_df)

matrix =user_friends_df.to_numpy()
matrix

friendID  2     3     4     5     6     7     8     9     10    11    ...  \
userID                                                                ...
2            0     0     0     0     0     0     0     0     0     0  ...
3            0     0     0     0     0     0     0     0     0     0  ...
4            0     0     0     0     0     0     0     0     0     0  ...
5            0     0     0     0     0     0     0     0     0     0  ...
6            0     0     0     0     0     0     0     0     0     0  ...
...        ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...
2095         0     0     0     0     0     0     0     0     0     0  ...
2096         0     0     0     0     0     0     0     0     0     0  ...
2097         0     0     0     0     0     0     0     0     0     0  ...
2099         0     0     0     0     0     0     0     0     0     0  ...
2100         0     0     0     0     0     0     0     0     0     0  ...

friendID  2090  2091  2092  2093  2094  2095  2096  2097  2099  2100
userID
2            0     0     0     0     0     0     0     0     0     0
3            0     0     0     0     0     0     0     0     0     0
4            0     0     0     0     0     0     0     0     0     0
5            0     0     0     0     0     0     0     0     0     0
6            0     0     0     0     0     0     0     0     0     0
...        ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
2095         0     0     0     0     0     0     0     0     0     0
2096         0     0     0     0     0     0     0     0     0     0
2097         0     0     0     0     0     0     0     0     0     0
2099         0     0     0     0     0     0     0     0     0     0
2100         0     0     0     0     0     0     0     0     0     0

[1892 rows x 1892 columns]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
useruser_dict = {i+1: index for i, index in enumerate(user_friends_df.index)}

In [ ]:
useruser_dict

{1: 2,
 2: 3,
 3: 4,
 4: 5,
 5: 6,
 6: 7,
 7: 8,
 8: 9,
 9: 10,
 10: 11,
 11: 12,
 12: 13,
 13: 14,
 14: 15,
 15: 16,
 16: 17,
 17: 18,
 18: 20,
 19: 21,
 20: 22,
 21: 23,
 22: 24,
 23: 25,
 24: 26,
 25: 27,
 26: 28,
 27: 29,
 28: 30,
 29: 31,
 30: 32,
 31: 33,
 32: 34,
 33: 35,
 34: 36,
 35: 37,
 36: 38,
 37: 39,
 38: 40,
 39: 41,
 40: 42,
 41: 43,
 42: 44,
 43: 45,
 44: 46,
 45: 47,
 46: 48,
 47: 49,
 48: 50,
 49: 51,
 50: 52,
 51: 53,
 52: 54,
 53: 55,
 54: 56,
 55: 57,
 56: 58,
 57: 59,
 58: 60,
 59: 61,
 60: 62,
 61: 63,
 62: 64,
 63: 65,
 64: 66,
 65: 68,
 66: 69,
 67: 70,
 68: 71,
 69: 72,
 70: 73,
 71: 74,
 72: 75,
 73: 76,
 74: 77,
 75: 78,
 76: 79,
 77: 80,
 78: 81,
 79: 82,
 80: 83,
 81: 84,
 82: 85,
 83: 86,
 84: 87,
 85: 88,
 86: 89,
 87: 90,
 88: 91,
 89: 92,
 90: 94,
 91: 95,
 92: 96,
 93: 97,
 94: 98,
 95: 99,
 96: 100,
 97: 101,
 98: 102,
 99: 103,
 100: 104,
 101: 105,
 102: 106,
 103: 107,
 104: 108,
 105: 109,
 106: 110,
 107: 111,
 108: 112,
 109: 113,
 110: 114,
 111: 115,
 112: 116,
 113: 117,
 114: 118,
 115: 119,
 116: 120,
 117: 121,
 118: 122,
 119: 123,
 120: 124,
 121: 125,
 122: 126,
 123: 127,
 124: 128,
 125: 129,
 126: 130,
 127: 131,
 128: 132,
 129: 133,
 130: 134,
 131: 135,
 132: 136,
 133: 137,
 134: 139,
 135: 140,
 136: 141,
 137: 142,
 138: 143,
 139: 144,
 140: 145,
 141: 146,
 142: 147,
 143: 148,
 144: 149,
 145: 150,
 146: 151,
 147: 152,
 148: 153,
 149: 154,
 150: 155,
 151: 156,
 152: 157,
 153: 158,
 154: 159,
 155: 161,
 156: 162,
 157: 163,
 158: 164,
 159: 166,
 160: 168,
 161: 170,
 162: 171,
 163: 172,
 164: 173,
 165: 174,
 166: 175,
 167: 176,
 168: 177,
 169: 178,
 170: 179,
 171: 180,
 172: 181,
 173: 182,
 174: 183,
 175: 184,
 176: 185,
 177: 186,
 178: 187,
 179: 188,
 180: 189,
 181: 190,
 182: 191,
 183: 192,
 184: 193,
 185: 194,
 186: 195,
 187: 196,
 188: 198,
 189: 200,
 190: 201,
 191: 202,
 192: 203,
 193: 204,
 194: 205,
 195: 206,
 196: 207,
 197: 208,
 198: 209,
 199: 210,
 200: 211,
 201: 212,
 202: 213,
 203: 214,
 204: 215,
 205: 216,
 206: 217,
 207: 218,
 208: 219,
 209: 220,
 210: 223,
 211: 224,
 212: 225,
 213: 226,
 214: 227,
 215: 228,
 216: 229,
 217: 230,
 218: 231,
 219: 232,
 220: 233,
 221: 234,
 222: 235,
 223: 236,
 224: 237,
 225: 238,
 226: 240,
 227: 241,
 228: 242,
 229: 243,
 230: 244,
 231: 247,
 232: 248,
 233: 249,
 234: 250,
 235: 251,
 236: 252,
 237: 253,
 238: 254,
 239: 255,
 240: 256,
 241: 257,
 242: 258,
 243: 259,
 244: 260,
 245: 261,
 246: 262,
 247: 263,
 248: 264,
 249: 265,
 250: 266,
 251: 267,
 252: 268,
 253: 269,
 254: 270,
 255: 271,
 256: 273,
 257: 274,
 258: 275,
 259: 277,
 260: 278,
 261: 279,
 262: 280,
 263: 281,
 264: 282,
 265: 283,
 266: 284,
 267: 285,
 268: 286,
 269: 288,
 270: 289,
 271: 290,
 272: 291,
 273: 292,
 274: 293,
 275: 294,
 276: 295,
 277: 296,
 278: 297,
 279: 298,
 280: 299,
 281: 300,
 282: 301,
 283: 302,
 284: 303,
 285: 304,
 286: 305,
 287: 306,
 288: 307,
 289: 308,
 290: 310,
 291: 311,
 292: 312,
 293: 313,
 294: 314,
 295: 315,
 296: 316,
 297: 317,
 298: 318,
 299: 319,
 300: 320,
 301: 321,
 302: 322,
 303: 324,
 304: 325,
 305: 326,
 306: 327,
 307: 328,
 308: 329,
 309: 330,
 310: 331,
 311: 332,
 312: 333,
 313: 334,
 314: 335,
 315: 336,
 316: 337,
 317: 338,
 318: 339,
 319: 340,
 320: 341,
 321: 342,
 322: 343,
 323: 344,
 324: 345,
 325: 346,
 326: 347,
 327: 348,
 328: 349,
 329: 350,
 330: 351,
 331: 352,
 332: 353,
 333: 354,
 334: 355,
 335: 356,
 336: 357,
 337: 358,
 338: 359,
 339: 360,
 340: 361,
 341: 362,
 342: 363,
 343: 364,
 344: 365,
 345: 366,
 346: 367,
 347: 368,
 348: 369,
 349: 370,
 350: 371,
 351: 372,
 352: 374,
 353: 375,
 354: 376,
 355: 377,
 356: 378,
 357: 380,
 358: 382,
 359: 383,
 360: 385,
 361: 386,
 362: 387,
 363: 388,
 364: 390,
 365: 391,
 366: 392,
 367: 393,
 368: 394,
 369: 395,
 370: 396,
 371: 397,
 372: 398,
 373: 399,
 374: 400,
 375: 401,
 376: 402,
 377: 403,
 378: 404,
 379: 405,
 380: 406,
 381: 407,
 382: 408,
 383: 409,
 384: 410,
 385: 411,
 386: 412,
 387: 413,
 388: 414,
 389: 415,
 390: 416,
 391: 417,
 392: 418,
 393: 419,
 394: 420,
 395: 421,
 396: 423,
 397: 424,
 398: 425,
 399: 426,
 400: 427,
 401: 428,
 402: 430,
 403: 431,
 404: 432,
 405: 433,
 406: 434,
 407: 435,
 408: 436,
 409: 437,
 410: 438,
 411: 439,
 412: 440,
 413: 441,
 414: 442,
 415: 443,
 416: 444,
 417: 446,
 418: 447,
 419: 449,
 420: 450,
 421: 451,
 422: 452,
 423: 453,
 424: 454,
 425: 455,
 426: 456,
 427: 457,
 428: 458,
 429: 459,
 430: 460,
 431: 461,
 432: 462,
 433: 463,
 434: 464,
 435: 465,
 436: 466,
 437: 467,
 438: 468,
 439: 469,
 440: 470,
 441: 471,
 442: 472,
 443: 473,
 444: 474,
 445: 475,
 446: 476,
 447: 477,
 448: 478,
 449: 479,
 450: 480,
 451: 481,
 452: 482,
 453: 484,
 454: 485,
 455: 486,
 456: 487,
 457: 488,
 458: 489,
 459: 490,
 460: 491,
 461: 492,
 462: 493,
 463: 494,
 464: 495,
 465: 496,
 466: 497,
 467: 498,
 468: 499,
 469: 500,
 470: 501,
 471: 502,
 472: 503,
 473: 504,
 474: 506,
 475: 507,
 476: 508,
 477: 509,
 478: 510,
 479: 511,
 480: 512,
 481: 513,
 482: 514,
 483: 515,
 484: 516,
 485: 517,
 486: 518,
 487: 519,
 488: 520,
 489: 521,
 490: 523,
 491: 525,
 492: 526,
 493: 527,
 494: 529,
 495: 530,
 496: 531,
 497: 532,
 498: 533,
 499: 534,
 500: 535,
 501: 536,
 502: 537,
 503: 538,
 504: 539,
 505: 540,
 506: 541,
 507: 542,
 508: 543,
 509: 544,
 510: 545,
 511: 546,
 512: 547,
 513: 548,
 514: 549,
 515: 550,
 516: 551,
 517: 552,
 518: 553,
 519: 555,
 520: 556,
 521: 557,
 522: 558,
 523: 559,
 524: 560,
 525: 561,
 526: 562,
 527: 563,
 528: 565,
 529: 566,
 530: 567,
 531: 568,
 532: 569,
 533: 570,
 534: 571,
 535: 572,
 536: 573,
 537: 574,
 538: 575,
 539: 576,
 540: 577,
 541: 578,
 542: 579,
 543: 580,
 544: 581,
 545: 582,
 546: 583,
 547: 584,
 548: 585,
 549: 586,
 550: 587,
 551: 589,
 552: 590,
 553: 592,
 554: 593,
 555: 594,
 556: 595,
 557: 596,
 558: 598,
 559: 601,
 560: 602,
 561: 603,
 562: 604,
 563: 605,
 564: 606,
 565: 607,
 566: 608,
 567: 609,
 568: 611,
 569: 612,
 570: 613,
 571: 614,
 572: 615,
 573: 616,
 574: 617,
 575: 618,
 576: 619,
 577: 620,
 578: 621,
 579: 622,
 580: 623,
 581: 624,
 582: 625,
 583: 627,
 584: 628,
 585: 629,
 586: 631,
 587: 632,
 588: 633,
 589: 634,
 590: 635,
 591: 636,
 592: 637,
 593: 638,
 594: 639,
 595: 640,
 596: 641,
 597: 642,
 598: 643,
 599: 644,
 600: 645,
 601: 646,
 602: 647,
 603: 649,
 604: 650,
 605: 651,
 606: 652,
 607: 654,
 608: 655,
 609: 656,
 610: 657,
 611: 658,
 612: 659,
 613: 660,
 614: 661,
 615: 662,
 616: 663,
 617: 664,
 618: 665,
 619: 666,
 620: 667,
 621: 668,
 622: 669,
 623: 670,
 624: 671,
 625: 672,
 626: 673,
 627: 674,
 628: 675,
 629: 676,
 630: 677,
 631: 678,
 632: 679,
 633: 680,
 634: 681,
 635: 682,
 636: 683,
 637: 684,
 638: 685,
 639: 686,
 640: 687,
 641: 688,
 642: 689,
 643: 690,
 644: 691,
 645: 692,
 646: 693,
 647: 694,
 648: 695,
 649: 696,
 650: 697,
 651: 698,
 652: 699,
 653: 700,
 654: 701,
 655: 702,
 656: 703,
 657: 704,
 658: 705,
 659: 706,
 660: 707,
 661: 708,
 662: 709,
 663: 710,
 664: 711,
 665: 712,
 666: 713,
 667: 714,
 668: 715,
 669: 716,
 670: 717,
 671: 718,
 672: 719,
 673: 720,
 674: 721,
 675: 722,
 676: 723,
 677: 725,
 678: 726,
 679: 727,
 680: 728,
 681: 729,
 682: 730,
 683: 731,
 684: 732,
 685: 733,
 686: 734,
 687: 735,
 688: 736,
 689: 737,
 690: 738,
 691: 739,
 692: 741,
 693: 742,
 694: 743,
 695: 744,
 696: 745,
 697: 746,
 698: 747,
 699: 749,
 700: 750,
 701: 751,
 702: 752,
 703: 753,
 704: 754,
 705: 756,
 706: 757,
 707: 758,
 708: 759,
 709: 760,
 710: 761,
 711: 762,
 712: 763,
 713: 764,
 714: 765,
 715: 767,
 716: 768,
 717: 769,
 718: 770,
 719: 771,
 720: 772,
 721: 773,
 722: 776,
 723: 777,
 724: 778,
 725: 779,
 726: 780,
 727: 781,
 728: 782,
 729: 784,
 730: 785,
 731: 786,
 732: 787,
 733: 788,
 734: 789,
 735: 790,
 736: 791,
 737: 792,
 738: 793,
 739: 794,
 740: 795,
 741: 797,
 742: 798,
 743: 799,
 744: 800,
 745: 801,
 746: 802,
 747: 804,
 748: 805,
 749: 806,
 750: 807,
 751: 808,
 752: 809,
 753: 810,
 754: 812,
 755: 813,
 756: 814,
 757: 815,
 758: 816,
 759: 817,
 760: 818,
 761: 819,
 762: 820,
 763: 821,
 764: 822,
 765: 823,
 766: 824,
 767: 825,
 768: 826,
 769: 827,
 770: 828,
 771: 829,
 772: 830,
 773: 831,
 774: 832,
 775: 834,
 776: 835,
 777: 836,
 778: 837,
 779: 838,
 780: 839,
 781: 840,
 782: 841,
 783: 842,
 784: 843,
 785: 844,
 786: 845,
 787: 846,
 788: 847,
 789: 848,
 790: 849,
 791: 850,
 792: 851,
 793: 852,
 794: 853,
 795: 854,
 796: 855,
 797: 856,
 798: 858,
 799: 859,
 800: 860,
 801: 861,
 802: 862,
 803: 863,
 804: 864,
 805: 865,
 806: 868,
 807: 869,
 808: 870,
 809: 871,
 810: 873,
 811: 874,
 812: 875,
 813: 876,
 814: 877,
 815: 878,
 816: 881,
 817: 882,
 818: 884,
 819: 885,
 820: 886,
 821: 887,
 822: 888,
 823: 889,
 824: 890,
 825: 891,
 826: 893,
 827: 895,
 828: 896,
 829: 897,
 830: 898,
 831: 899,
 832: 900,
 833: 903,
 834: 904,
 835: 905,
 836: 906,
 837: 907,
 838: 908,
 839: 909,
 840: 910,
 841: 911,
 842: 912,
 843: 913,
 844: 914,
 845: 915,
 846: 916,
 847: 917,
 848: 919,
 849: 920,
 850: 921,
 851: 922,
 852: 924,
 853: 925,
 854: 926,
 855: 927,
 856: 928,
 857: 929,
 858: 930,
 859: 931,
 860: 932,
 861: 933,
 862: 934,
 863: 935,
 864: 936,
 865: 938,
 866: 939,
 867: 940,
 868: 941,
 869: 942,
 870: 943,
 871: 946,
 872: 948,
 873: 949,
 874: 950,
 875: 951,
 876: 952,
 877: 953,
 878: 954,
 879: 955,
 880: 957,
 881: 958,
 882: 959,
 883: 960,
 884: 961,
 885: 962,
 886: 963,
 887: 964,
 888: 965,
 889: 966,
 890: 967,
 891: 968,
 892: 969,
 893: 971,
 894: 972,
 895: 975,
 896: 976,
 897: 977,
 898: 978,
 899: 979,
 900: 980,
 901: 981,
 902: 982,
 903: 984,
 904: 985,
 905: 986,
 906: 987,
 907: 989,
 908: 990,
 909: 991,
 910: 993,
 911: 994,
 912: 995,
 913: 996,
 914: 997,
 915: 998,
 916: 999,
 917: 1001,
 918: 1002,
 919: 1003,
 920: 1004,
 921: 1005,
 922: 1006,
 923: 1007,
 924: 1008,
 925: 1009,
 926: 1010,
 927: 1011,
 928: 1012,
 929: 1013,
 930: 1014,
 931: 1015,
 932: 1016,
 933: 1017,
 934: 1018,
 935: 1019,
 936: 1020,
 937: 1021,
 938: 1022,
 939: 1023,
 940: 1024,
 941: 1025,
 942: 1026,
 943: 1027,
 944: 1028,
 945: 1029,
 946: 1030,
 947: 1032,
 948: 1033,
 949: 1034,
 950: 1035,
 951: 1036,
 952: 1037,
 953: 1038,
 954: 1039,
 955: 1040,
 956: 1041,
 957: 1042,
 958: 1044,
 959: 1046,
 960: 1047,
 961: 1049,
 962: 1050,
 963: 1051,
 964: 1052,
 965: 1053,
 966: 1054,
 967: 1055,
 968: 1056,
 969: 1057,
 970: 1058,
 971: 1060,
 972: 1061,
 973: 1062,
 974: 1063,
 975: 1064,
 976: 1065,
 977: 1067,
 978: 1068,
 979: 1069,
 980: 1070,
 981: 1071,
 982: 1072,
 983: 1073,
 984: 1074,
 985: 1075,
 986: 1076,
 987: 1078,
 988: 1079,
 989: 1080,
 990: 1081,
 991: 1082,
 992: 1083,
 993: 1084,
 994: 1085,
 995: 1086,
 996: 1087,
 997: 1088,
 998: 1089,
 999: 1090,
 1000: 1091,
 ...}

In [ ]:
matrix.shape

(1892, 1892)

In [ ]:
df = pd.DataFrame(matrix)
df

,0,1,2,3,4,5,6,7,8,9,...,1882,1883,1884,1885,1886,1887,1888,1889,1890,1891
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1887,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1888,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1889,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1890,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1891,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
df.to_csv('user_user.csv', index=False)

##User-Tag

In [ ]:
user_tagged = pd.read_csv("/content/hetrec2011-lastfm-2k/user_taggedartists.csv")
user_tagged

        userID  artistID  tagID  day  month  year
0            2        52     13    1      4  2009
1            2        52     15    1      4  2009
2            2        52     18    1      4  2009
3            2        52     21    1      4  2009
4            2        52     41    1      4  2009
...        ...       ...    ...  ...    ...   ...
186474    2100     16437      4    1      7  2010
186475    2100     16437    292    1      5  2010
186476    2100     16437   2087    1      7  2010
186477    2100     16437   2801    1      5  2010
186478    2100     16437   3335    1      7  2010

[186479 rows x 6 columns]

In [ ]:
max_userID = user_tagged['artistID'].max(axis = 0)
max_userID

18744

In [ ]:
# Create a pivot table with index starting at zero and ending at 2100
pivot_table = user_tagged.pivot_table(index=['userID'], columns='tagID', aggfunc = 'size').fillna(0)

# Reindex the pivot table to have index from 0 to 2100
# user_tag_df = pivot_table.reindex(range(1, 2101), fill_value=0, axis=0).reindex(range(1, 12649), fill_value=0, axis=1)
user_tag_df = pivot_table
# Reset column names to be 'userID' and 'friendID'
user_tag_df.columns.name = 'tagID'
user_tag_df.index.name = 'userID'

print(user_tag_df)

user_tag_matrix =user_tag_df.to_numpy()
user_tag_matrix

tagID   1      2      3      4      5      6      7      8      9      10     \
userID
2         0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
3         0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
4         1.0    0.0    0.0    0.0    0.0    1.0    1.0    0.0    0.0    0.0
5         0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
6         0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
...       ...    ...    ...    ...    ...    ...    ...    ...    ...    ...
2095      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
2096      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
2097      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
2099      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
2100      0.0    0.0    0.0    3.0    0.0    0.0    0.0    0.0    0.0    0.0

tagID   ...  12638  12639  12640  12641  12642  12643  12644  12645  12646  \
userID  ...
2       ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
3       ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
4       ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
5       ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
6       ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
...     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...
2095    ...   29.0   31.0   13.0   12.0    0.0    0.0    0.0    0.0    0.0
2096    ...    0.0    0.0    0.0    0.0   39.0    7.0    6.0    4.0    6.0
2097    ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
2099    ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
2100    ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0

tagID   12647
userID
2         0.0
3         0.0
4         0.0
5         0.0
6         0.0
...       ...
2095      0.0
2096      6.0
2097      0.0
2099      0.0
2100      0.0

[1892 rows x 9749 columns]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
np.unique(user_tag_df)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
       65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
       78., 79., 80., 81., 82., 84., 85., 86., 87., 88., 90., 92., 93.,
       94., 95., 96.])

In [ ]:
user_tag_matrix = np.where(user_tag_matrix>1,1,0)

In [ ]:
df = pd.DataFrame(user_tag_matrix)
df

,0,1,2,3,4,5,6,7,8,9,...,9739,9740,9741,9742,9743,9744,9745,9746,9747,9748
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1887,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,0,0,0,0,0,0
1888,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,1,1,1,1,1
1889,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1890,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1891,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
df.to_csv('user_tag.csv', index=False)

##User-Item

In [ ]:
user_item = pd.read_csv("/content/hetrec2011-lastfm-2k/user_taggedartists.csv")
user_item

        userID  artistID  tagID  day  month  year
0            2        52     13    1      4  2009
1            2        52     15    1      4  2009
2            2        52     18    1      4  2009
3            2        52     21    1      4  2009
4            2        52     41    1      4  2009
...        ...       ...    ...  ...    ...   ...
186474    2100     16437      4    1      7  2010
186475    2100     16437    292    1      5  2010
186476    2100     16437   2087    1      7  2010
186477    2100     16437   2801    1      5  2010
186478    2100     16437   3335    1      7  2010

[186479 rows x 6 columns]

In [ ]:
max_userID = user_tagged['tagID'].max(axis = 0)
max_userID

12647

In [ ]:

# Create a pivot table with index starting at zero and ending at 2100
pivot_table = user_item.pivot_table(index=['userID'], columns='artistID', aggfunc = 'size').fillna(0)

# Reindex the pivot table to have index from 0 to 2100
# user_item_df = pivot_table.reindex(range(1, 2101), fill_value=0, axis=0).reindex(range(1, 18746), fill_value=0, axis=1)
user_item_df = pivot_table
# Reset column names to be 'userID' and 'friendID'
user_item_df.columns.name = 'artistID'
user_item_df.index.name = 'userID'

print(user_item_df)

user_item_matrix =user_item_df.to_numpy()
user_item_matrix

artistID  1      2      3      4      5      6      7      8      9      \
userID
2           0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
3           0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
4           0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
5           0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
6           0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
...         ...    ...    ...    ...    ...    ...    ...    ...    ...
2095        0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
2096        0.0    0.0    0.0    0.0    0.0    0.0    2.0    0.0    0.0
2097        0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
2099        0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
2100        0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0

artistID  10     ...  18724  18732  18734  18735  18736  18737  18739  18740  \
userID           ...
2           0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
3           0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
4           0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
5           0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
6           0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
...         ...  ...    ...    ...    ...    ...    ...    ...    ...    ...
2095        0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
2096        0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    1.0    0.0
2097        0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
2099        0.0  ...    3.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
2100        0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0

artistID  18741  18744
userID
2           0.0    0.0
3           0.0    0.0
4           0.0    0.0
5           0.0    0.0
6           0.0    0.0
...         ...    ...
2095        0.0    0.0
2096        0.0    0.0
2097        0.0    0.0
2099        0.0    0.0
2100        0.0    0.0

[1892 rows x 12523 columns]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
user_item_df[2096].loc[user_item_df[2096]==1]

Series([], Name: 2096, dtype: float64)

In [ ]:
np.unique(user_item_df)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [ ]:
user_item_matrix = np.where(user_item_matrix>1,1,0)

In [ ]:
np.unique(user_item_matrix)

array([0, 1])

In [ ]:
df = pd.DataFrame(user_item_matrix)
df

,0,1,2,3,4,5,6,7,8,9,...,12513,12514,12515,12516,12517,12518,12519,12520,12521,12522
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1887,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1888,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1889,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1890,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
1891,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
df.to_csv('user_item.csv', index=False)

In [ ]:
!jupyter nbconvert --to html --output I040,I057_Input_RS_Project.html I040,_I057_Input_RS_Project.ipynb

[NbConvertApp] Converting notebook I040,_I057_Input_RS_Project.ipynb to html
[NbConvertApp] Writing 690721 bytes to I040,I057_Input_RS_Project.html